<?php

/**
 * Model_AdminUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_AdminUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_AdminUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_AdminUser');
    }

    public function fetchOneByCredentials($email, $password)
    {
      $q = $this->createQuery('u')->where('u.email = ?', $email)
                                  ->andWhere('u.password = sha1(CONCAT(password_salt, ?))', $password)
                                  ->limit(1);

      return $q->fetchOne();
    }
}