<?php

/**
 * Model_ApnsDeviceHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_ApnsDeviceHistoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_ApnsDeviceHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_ApnsDeviceHistory');
    }
}