<?php

/**
 * Model_ApnsDeviceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_ApnsDeviceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_ApnsDeviceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_ApnsDevice');
    }
}