<?php

/**
 * Model_ApnsMessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_ApnsMessageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_ApnsMessageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_ApnsMessage');
    }
}