<?php

/**
 * Model_EditorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_EditorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_EditorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Editor');
    }
}