<?php

/**
 * Model_TrackingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_TrackingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_TrackingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Tracking');
    }
}